version: "3.9"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=$DATABASE_HOSTNAME
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - SECRET_KEY=$SECRET_KEY
      - ALGORITHM=$ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - mysql-service
    networks:
      api_network:
        ipv4_address: 192.168.1.6

  mysql-service:
    image: mysql/mysql-server:8.0.32
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--init-file"
      - "/docker-entrypoint-initdb.d/init.sql"
    container_name: mysql
    environment:
      MYSQL_RmysqlOOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: $POSTGRES_DB
      MYSQL_ONETIME_PASSWORD: True
    volumes:
        - mysql-db:/var/lib/mysql
        - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      api_network:
        ipv4_address: 192.168.1.3
    ports:
        - "3307:3307"
  adminer-service:
    image: adminer:latest
    restart: unless-stopped
    container_name: adminer
    networks:
      api_network:
        ipv4_address: 192.168.1.4
    depends_on:
      - mysql-service
    ports:
      - "8080:8080"
  mailsender:
    image: mailhog/mailhog
    restart: unless-stopped
    container_name: mail_sender
    networks:
      api_network:
        ipv4_address: 192.168.1.5
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:

  mysql-db:
    #external: true
networks:
  api_network:
    driver: default
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.0/24
    external: true

