version: "3"
services:
  api:
    build: .
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    # env_file:
    #     - ./.env
    environment:
      - DATABASE_HOSTNAME=$DATABASE_HOSTNAME
      - DATABASE_PORT=$DATABASE_PORT
      - DATABASE_PASSWORD=$DATABASE_PASSWORD
      - DATABASE_NAME=$DATABASE_NAME
      - DATABASE_USERNAME=$DATABASE_USERNAME
      - SECRET_KEY=$SECRET_KEY
      - ALGORITHM=$ALGORITHM
      - ACCESS_TOKEN_EXPIRE_MINUTES=$ACCESS_TOKEN_EXPIRE_MINUTES
    command: uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=$POSTGRES_PASSWORD
      - POSTGRES_DB=$POSTGRES_DB
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
        - "5432:5432"

  mysql-service:
    image: mysql/mysql-server:8.0.32
    command: [ "--default-authentication-plugin=mysql_native_password" ]
    container_name: mysql
    environment:
      MYSQL_RmysqlOOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: $POSTGRES_DB
    volumes:
        - /var/lib/mysql
    ports:
        - "3307:3307"
  adminer-service:
    image: adminer:latest
    restart: unless-stopped
    container_name: adminer
    depends_on:
      - postgres
    ports:
      - "8080:8080"
  mailsender:
    image: mailhog/mailhog
    restart: unless-stopped
    container_name: mail_sender
    ports:
      - "8025:8025"
      - "1025:1025"

volumes:
  postgres-db:
